@startuml
start
:Init a = 0, b = 1, result = 0;
if (n <= 1) then (yes)
    :return n;
else (no)
    :i = 2 to n;
    while (i <= n?) is (yes)
        :result = a + b;
        :a = b;
        :b = result;
        :i++;
    endwhile
    :return result;
endif
stop
@enduml
