@startuml
[*] --> Init
Init --> dp_0 : dp[0] = 0
dp_0 --> dp_1 : dp[1] = 1
dp_1 --> Loop : i = 2
Loop --> Calculate : dp[i] = dp[i-1] + dp[i-2]
Calculate --> Loop : i++
Loop --> End : Return dp[n]
End --> [*]
@enduml

